version: '3'

services:
  py-mongosql-postgres-test:
    image: postgres
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_mongosql
